global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fraud_detection_service"
    static_configs:
      - targets: ["fraud-detection-service:8001"]
      
  - job_name: "transaction_service"
    static_configs:
      - targets: ["transaction-service:80"]

  - job_name: 'user-account-service'
    static_configs:
      - targets: ['user-account-service:80']

