apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: elasticsearch
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: elasticsearch
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:9200/_cluster/health || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata
