apiVersion: v1
kind: Service
metadata:
  annotations:
    app: elasticsearch
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: elasticsearch
  type: NodePort
