apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: fraud-detection-service:latest
          imagePullPolicy: Never # Use the local image, don’t try to pull from a registry
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.default.svc.cluster.local"
