apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: fraud-detection-service
  name: fraud-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fraud-detection-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: fraud-detection-service
    spec:
      containers:
        - args:
            - uvicorn
            - main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          image: fhallengreen/dls_banking_app-fraud-detection-service:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000/health
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: fraud-detection-service
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          resources:
            limits:
              memory: "268435456"
      restartPolicy: Always
