apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: grafana
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: grafana
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - sleep 10 && /run.sh
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_SECURITY_ADMIN_USER
          image: grafana/grafana:latest
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "134217728"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      restartPolicy: Always
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
