apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: mysql-useraccount
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: clusterip
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mysql-useraccount
  name: mysql-useraccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-useraccount
  template:
    metadata:
      annotations:
        app: mysql-useraccount
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.image-pull-policy: Always
        kompose.service.type: clusterip
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: mysql-useraccount
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-app-secret
                  key: MYSQL_PASSWORD_UA
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: banking-app-config
                  key: MYSQL_DATABASE_UA
          image: mysql:8.0
          imagePullPolicy: Always
          name: mysql-useraccount
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-useraccount-data
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "536870912"
      volumes:
        - name: mysql-useraccount-data
          persistentVolumeClaim:
            claimName: mysql-useraccount-data
        - name: init-scripts
          configMap:
            name: mysql-useraccount-config
      restartPolicy: Always