apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: prometheus
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        app: prometheus
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.image-pull-policy: Always
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:latest
          imagePullPolicy: Always
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          resources:
            limits:
              memory: "268435456"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
      restartPolicy: Always