apiVersion: v1
kind: Service
metadata:
  annotations:
    app: rabbitmq
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "amqp" # Renamed from "5672"
      port: 5672
      targetPort: 5672
    - name: "management" # Renamed from "15672"
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort # Kept as NodePort for management UI access, AMQP could be ClusterIP if only internal
