apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: rabbitmq
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      annotations:
        app: rabbitmq
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.image-pull-policy: Always
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: banking-app-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: banking-app-secret
                  key: RABBITMQ_DEFAULT_PASS
          image: rabbitmq:3-management
          imagePullPolicy: Always
          name: rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          resources:
            limits:
              memory: "536870912"
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
      restartPolicy: Always