apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: redis
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        app: redis
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.service.type: nodeport
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:6.2
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: "67108864"
      restartPolicy: Always
