apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: redis
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: clusterip
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        app: redis
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.image-pull-policy: Always
        kompose.service.type: clusterip
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.2
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: "67108864"
      restartPolicy: Always