apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: transaction-service
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transaction-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.prod.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: transaction-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: JWT_AUDIENCE
              value: UserAccountAPI
            - name: JWT_ISSUER
              value: BankingApp
            - name: JWT_KEY
              value: bcdae8cd5aa9e33539156c046f496a6d083180d2fdd8a19140e85b6a2f6cf4e5cf3dbef80150f781fcb6b1a4b8e4e2307cb14c16a137895fe14bc1df88d667731b8cc50b550466ec8d3e349fee6558e4cd0b2bd626fc8b2e3c24c4202588903ba47f4a552d22b9c4f8f4ddafc8f612e6202cbc08c626496911e4413e30600bf4
            - name: MYSQL_DATABASE
              value: transaction_db
            - name: MYSQL_HOST
              value: mysql-transaction
            - name: MYSQL_PASSWORD
              value: password1!
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: PROMETHEUS_PORT
              value: "9091"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: Services__UserAccountService
              value: http://user-account-service:80
            - name: TRANSACTION_SERVICE_TOKEN
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0cmFuc2FjdGlvbi1zZXJ2aWNlIiwicm9sZSI6InNlcnZpY2UiLCJzY29wZXMiOlsicmVhZDphY2NvdW50cyIsInVwZGF0ZTphY2NvdW50LWJhbGFuY2UiXSwianRpIjoiNzAwOGE1M2MtNWQxYy00MGMyLTk2Y2UtZjk1YWJmY2Q2NzM4IiwiZXhwIjoxNzYxMjQyNTQ1LCJpc3MiOiJCYW5raW5nQXBwIiwiYXVkIjoiVXNlckFjY291bnRBUEkifQ.A43d7RphLWti6SVPf0oalb72OaUcy-88NlvA9Q_v1cQ"
          image: fhallengreen/dls_banking_app-transaction-service:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:80/health
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          name: transaction-service
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
      restartPolicy: Always
