apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP for internal service
  selector:
    app: transaction-service
  ports:
    - name: http
      protocol: TCP
      port: 8003  # Service port for application
      targetPort: 8080 # Container port for application
    - name: metrics
      protocol: TCP
      port: 9092  # Service port for metrics
      targetPort: 9092 # Container port for metrics