apiVersion: v1
kind: Service
metadata:
  annotations:
    app: transaction-service
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: transaction-service
  name: transaction-service
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 80
    - name: "9092"
      port: 9092
      targetPort: 9091
  selector:
    io.kompose.service: transaction-service
  type: NodePort
