apiVersion: v1
kind: Service
metadata:
  annotations:
    app: user-account-service
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: user-account-service
    app: user-account-service
  name: user-account-service
spec:
  type: NodePort
  ports:
    - name: "8002-80"
      port: 8002
      targetPort: 80
      protocol: TCP
    - name: "9091-9091"
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: user-account-service