apiVersion: v1
kind: Service
metadata:
  annotations:
    app: user-account-service
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.image-pull-policy: Always
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: user-account-service
    app: user-account-service
  name: user-account-service
spec:
  type: NodePort
  ports:
    - name: "8002" # This is the service port
      port: 8002
      targetPort: http # Should target the named port 'http' (8080) on the pod
      protocol: TCP
    - name: "9091"
      port: 9091
      targetPort: prometheus # Targets the named port 'prometheus' (9091) on the pod
      protocol: TCP
  selector:
    app: user-account-service