apiVersion: v1
kind: Service
metadata:
  annotations:
    app: user-account-service
    kompose.cmd: kompose convert -f ../docker-compose.prod.yml
    kompose.service.type: nodeport
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: user-account-service
  name: user-account-service
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 80
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: user-account-service
  type: NodePort
