name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push fraud-detection-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-fraud-detection-service:latest ./Microservices/FraudDetectionService
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-fraud-detection-service:latest

      - name: Build and push user-account-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-user-account-service:latest ./Microservices/UserAccountService
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-user-account-service:latest

      - name: Build and push transaction-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-transaction-service:latest ./Microservices/TransactionService
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-transaction-service:latest

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dls_banking_app-frontend:latest